#!/bin/sh /etc/rc.common

START=52
USE_PROCD=1

DAEMON=/usr/local/bin/librespot
LOGFILE=/var/log/spotify.log

OPTIONS="--name XiaomiSpeaker \
         --backend alsa \
         --device default \
         --format S16 \
         --bitrate 320 \
         --enable-volume-normalisation \
         --initial-volume 70 \
         --verbose"

start_service() {
    # Attendre que le réseau soit prêt (évite early EOF)
    sleep 3

    procd_open_instance
    procd_set_param command $DAEMON $OPTIONS
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 5
    procd_close_instance
}

stop_service() {
    killall -9 librespot 2>/dev/null
}
