#!/bin/sh
# ©2019 WifiRadio.su
fav="$QUERY_STRING"
st=$(uci get wifiradio.@fav[0].$fav)

uci set wifiradio.@setting[0].current=$st
uci commit wifiradio
/etc/wifiradio/play.sh
echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>
<body>"