#!/bin/sh
# ©2019 WifiRadio.su
echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>
<body>"

pop=$(uci get wifiradio.@subscribe[0].pop)
retro=$(uci get wifiradio.@subscribe[0].retro)
shanson=$(uci get wifiradio.@subscribe[0].shanson)
rock=$(uci get wifiradio.@subscribe[0].rock)
rap=$(uci get wifiradio.@subscribe[0].rap)
group=$(uci get wifiradio.@subscribe[0].group)
dance=$(uci get wifiradio.@subscribe[0].dance)
kids=$(uci get wifiradio.@subscribe[0].kids)
relax=$(uci get wifiradio.@subscribe[0].relax)
vostok=$(uci get wifiradio.@subscribe[0].vostok)
other=$(uci get wifiradio.@subscribe[0].other)
aac=$(uci get wifiradio.@subscribe[0].aac)

auto=$(uci get wifiradio.@setting[0].autoupdate)

echo "<table border='0' width='100%' style='font-family: Tahoma; font-size: 10pt' cellspacing='1'>
					<tr>
						<td width='5%'>"
if [ $auto -eq 1 ]
then
echo "<a href='../cgi-bin/wr_autostatusch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_autostatusch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo "</td>
						<td width='95%'>Update playlist after start</td>
						</tr>
					<tr>
						<td width='100%' colspan='2'>
						</td>
						</tr>
					</table>"
					
echo "<p><a class='button' href='../cgi-bin/wr_update'>Update playlist from server</a></p>"
echo "<hr color='#378D87' size='1'>"

echo								"<table border='0' width='100%' style='font-family: Tahoma; font-size: 8pt; color: #000000' cellspacing='1'>
									<tr>
										<td colspan='4' height='7'></td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $pop -eq 1 ]
then
echo "<a href='../cgi-bin/wr_pop_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_pop_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Pop</td>
										<td width='45'>"
										
if [ $retro -eq 1 ]
then
echo "<a href='../cgi-bin/wr_retro_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_retro_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Retro</td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $shanson -eq 1 ]
then
echo "<a href='../cgi-bin/wr_shanson_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_shanson_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Shanson</td>
										<td width='45'>"
										
if [ $rock -eq 1 ]
then
echo "<a href='../cgi-bin/wr_rock_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_rock_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Rock</td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $rap -eq 1 ]
then
echo "<a href='../cgi-bin/wr_rap_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_rap_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Hip-Hop / RnB</td>
										<td width='45'>"
										
if [ $group -eq 1 ]
then
echo "<a href='../cgi-bin/wr_group_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_group_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Discography</td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $dance -eq 1 ]
then
echo "<a href='../cgi-bin/wr_dance_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_dance_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Dance</td>
										<td width='45'>"
										
if [ $kids -eq 1 ]
then
echo "<a href='../cgi-bin/wr_kids_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_kids_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Kids</td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $relax -eq 1 ]
then
echo "<a href='../cgi-bin/wr_relax_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_relax_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Relax</td>
										<td width='45'>"
										
if [ $vostok -eq 1 ]
then
echo "<a href='../cgi-bin/wr_vostok_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_vostok_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Eastern</td>
									</tr>
									<tr>
										<td width='45'>"
										
if [ $other -eq 1 ]
then
echo "<a href='../cgi-bin/wr_other_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_other_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;Other</td>
										<td width='45'>"
if [ $aac -eq 1 ]
then
echo "<a href='../cgi-bin/wr_aac_ch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_aac_ch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo								"</td>
										<td class='subs' width='40%'>&nbsp;AAC+, OGG</td>
									</tr>
								</table>"
								
echo "<br>"

echo "<table border='0' width='100%' cellpadding='2'>"
echo "	<tr>"
echo "		<td width='10%'><a class='button' href='../cgi-bin/wr_all'>Enable&nbsp;all&nbsp;subscription</a></td>"
echo "		<td><a class='button' href='../cgi-bin/wr_clear'>Disable all subscription</a></td>"
echo "	</tr>"
echo "</table>"
