#!/bin/sh
# ©2019 WifiRadio.su
echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>
<body>"

sound=$(uci get wifiradio.@setting[0].sound)

echo "<form method='GET' target='op' action='../cgi-bin/wr_vol' onsubmit='return false' oninput='level.value = flevel.valueAsNumber'>"
echo "<output for='flying' name='level'>"
amixer get mysoftvol | grep 'Front Left:' |  awk '{ print $4 }' | grep -Eo '[0-9]+'
echo "</output>%<br>"
echo "<input name='flevel' onchange='submit();' id='flying' type='range' min='1' max='100' value="
amixer get $sound | grep 'Front Left: Playback' | awk '{ print $5 }' | grep -Eo '[0-9]+'
echo " step='1'>"
echo "</form>"