#!/bin/sh /etc/rc.common

START=91

USE_PROCD=1


start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/linein

  procd_set_param respawn
  procd_append_param respawn 3600
  procd_append_param respawn 5
  procd_append_param respawn 5
  procd_close_instance
}

service_started() {
    #renice -n-5 -p
    true
}

