#!/bin/sh
# ©2019 WifiRadio.su
IFS="&"
set -- $QUERY_STRING

nm=$1
ln=$2

name=${nm//name=/}
link=${ln//link=/}

n=$(echo -e `echo $name | sed 's/+/ /g;s/%/\\\\x/g;'`)
l=$(echo -e `echo $link | sed 's/+/ /g;s/%/\\\\x/g;'`)

echo -e "#EXTINF:-1,"$n"\n"$l >> /etc/wifiradio/user.m3u

sleep 1

cat "/etc/wifiradio/user.m3u" "/etc/wifiradio/wifiradio.su.m3u" > "/etc/wifiradio/playlist.m3u"

sleep 1

mpc clear
mpc load playlist.m3u
mpc play

echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Radio</title>"

echo "<script>
window.location.replace('wr_liststation');
</script>
<body>"
