#!/bin/sh
# ©2019 WifiRadio.su
echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>"

log=$((1))
cur=$(uci get wifiradio.@setting[0].current)

while read STATION

do

if [ $log -eq 3 ]
then
log=$((1))
fi

if [ $log -eq 2 ]
then
log=$(($log+1))
fi

num=$(($num + 1))
if [ $log -eq 1 ]
then
st=$(($num+1))
nn=$(($st/2))

for variable in 00 01 02 03 04 05 06 07 08 09 10
do
fav=$(uci get wifiradio.@fav[0].$variable)
if [ $fav -eq $st ]
then
echo "<list>★ ${STATION//#EXTINF:-1,/} ★</list>"
echo "<code>$st</code>"
fi
done

log=$(($log+1))

fi

done < /etc/wifiradio/playlist.m3u