#!/bin/sh
# ©2019 WifiRadio.su
uci set wifiradio.@subscribe[0].retro=$QUERY_STRING
uci commit wifiradio

/www/cgi-bin/wr_split

echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>
<script>
window.location.replace('../play/');
</script>
<body>"
