#!/bin/sh
# ©2019 WifiRadio.su
uci set wifiradio.@setting[0].time=$QUERY_STRING
uci commit wifiradio

echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Радио</title>
<script>
window.location.replace('../play/settings.htm');
</script>
<body>"
