#!/bin/sh
# ©2019 WifiRadio.su
echo "Content-type: text/html; charset=utf-8"
echo
echo "
<title>Wifi Radio</title>
<body>"

voice=$(uci get wifiradio.@setting[0].voice)
tts=$(uci get wifiradio.@setting[0].tts)
wheater=$(uci get wifiradio.@setting[0].wheater)
time=$(uci get wifiradio.@setting[0].time)
hello=$(uci get wifiradio.@setting[0].hello)
city=$(uci get wifiradio.@setting[0].city)

echo "<table border='0' width='100%' style='font-family: Tahoma; font-size: 10pt' cellspacing='1'>"
echo "<tr><td width='5%'>"

if [ $voice -eq 1 ]
then
echo "<a href='../cgi-bin/wr_voicech?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_voicech?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo "</td>"
echo "<td width='95%' class='subs'>&nbsp;Название станций</td>"
echo "</tr>"
echo "<tr><td width='5%'>"

if [ $time -eq 1 ]
then
echo "<a href='../cgi-bin/wr_timech?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_timech?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo "</td>"
echo "<td width='95%' class='subs'>&nbsp;Time</td>"
echo "</tr>"
echo "<tr><td width='5%'>"

if [ $wheater -eq 1 ]
then
echo "<a href='../cgi-bin/wr_wheaterch?0'><img border='0' src='img/on.png' title='Disable' alt='Disable'></a>"
else
echo "<a href='../cgi-bin/wr_wheaterch?1'><img border='0' src='img/off.png' title='Enable' alt='Enable'></a>"
fi

echo "</td>"
echo "<td width='95%' class='subs'>&nbsp;Weather</td>"
echo "</tr></table>"

echo "<hr color='#378D87' size='1'>"

hello=${hello//-/}
city=${city//-/}

echo "<form method='GET' action='../cgi-bin/wr_hello'>"

echo "<table border='0' width='100%' style='font-family: Tahoma; font-size: 10pt'>"
echo	"<tr>"
echo	"	<td>Voice:</td>"
echo	"	<td>"
echo	"<select size='1' name='tts' class='input'>"

echo	"	<option value='1'"
if [ $tts -eq 1 ]
then
echo "selected"
fi
echo ">&#9792; Female</option>"

echo	"	<option value='2'"
if [ $tts -eq 2 ]
then
echo "selected"
fi
echo ">&#9794; Male</option>"


echo	"</select>"
echo	"</td>"
echo	"</tr>"
echo	"<tr>"
echo	"	<td>Hello:</td>"
echo	"	<td><input type='text' name='name' size='35'  maxlength='60'  class='input' value='$hello'></td>"
echo	"</tr>"
echo	"<tr>"
echo	"	<td>City:</td>"
echo	"	<td><input type='text' name='city' size='35'  maxlength='60'  class='input' value='$city'></td>"
echo	"</tr>"
echo "</table>"

echo "<p><input class='button' type='submit' value='Save' name='send'></p>"
echo "</form>"