#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

DAEMON="/opt/audio-system/manager/auto_switch.sh"

start_service() {
    [ -x "$DAEMON" ] || return 1

    procd_open_instance
    procd_set_param command "$DAEMON"
    procd_set_param respawn
    procd_append_param respawn 3600 5 5
    procd_close_instance
}

stop_service() {
    killall -9 auto_switch.sh 2>/dev/null
}
